gems:
  - jekyll-gallery-generator
defaults:
  -
    scope:
      path: ""
    values:
      layout: "page"

# some configuration files have names which cannot start with underscores
# list them here for exclusion.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
